import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import vm from 'node:vm'

const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8')
const source=read('src-tauri/src/qmplus_linux_ipc.rs')
// Exact test-only upstream sources, with their original dual-license notices:
// https://github.com/tauri-apps/tauri/tree/tauri-v2.12.1/crates/tauri/scripts
const upstreamIpc=read('test/fixtures/tauri-2.12.1/ipc.js')
const upstreamCore=read('test/fixtures/tauri-2.12.1/core.js')
const raw=name=>source.match(new RegExp(`const ${name}: &str = r#"([\\s\\S]*?)"#;`))[1]
const stock=raw('STOCK_IPC_SCRIPT'),serializer=raw('STOCK_PROCESS_IPC_MESSAGE'),dispatch=raw('QMPLUS_DISPATCH')
const hash=value=>createHash('sha256').update(value).digest('hex')
const render=(candidate=true,os='linux')=>stock
  .replace('__TEMPLATE_invoke_key__','"fixture-invoke-key"')
  .replace('__RAW_process_ipc_message_fn__',serializer)
  .replace('__TEMPLATE_os_name__',JSON.stringify(os))
  .replace('__TEMPLATE_fetch_channel_data_command__','"plugin:__TAURI_CHANNEL__|fetch"')
  .replace('function sendIpcMessage(message) {',candidate?dispatch:'function sendIpcMessage(message) {')
const permissionCommands=identifier=>{
  const file=identifier.replace(/^allow-/,'').replaceAll('-','_')
  const permission=read(`src-tauri/permissions/autogenerated/${file}.toml`)
    .split('[[permission]]').find(block=>block.includes(`identifier = "${identifier}"`))
  assert.ok(permission,identifier)
  return JSON.parse(permission.match(/commands\.allow = (\[[^\n]+\])/)[1])
}
const mainCommands=JSON.parse(read('src-tauri/capabilities/default.json')).permissions
  .filter(identifier=>identifier.startsWith('allow-')).flatMap(permissionCommands)
const capabilities=['src-tauri/capabilities/qmplus.json','src-tauri/capabilities/qmplus-verification.json'].map(path=>{
  const capability=JSON.parse(read(path)),commands=capability.permissions.flatMap(permissionCommands)
  return {...capability,patterns:capability.remote.urls.map(pattern=>new URLPattern(pattern)),commands:new Set(commands)}
})
const tenant='https://login.microsoftonline.com/569df091-b013-40e3-86ee-bd9cb9e25814/saml2'
const flush=async()=>{for(let i=0;i<4;i++)await new Promise(resolve=>setImmediate(resolve))}

function fixture({candidate=true,label='qmplus',windowLabel=label,page=tenant,fetchMode='ok',reject=false,response=true,os='linux',deferMetadata=false,actualCore=false}={}) {
  const messages=[],fetches=[],warnings=[]
  let context
  const permitted=(url,command)=>label==='main'
    ?new URL(url).origin==='http://localhost:5173'
    :capabilities.some(capability=>capability.windows.includes(windowLabel)
      &&capability.commands.has(command)&&capability.patterns.some(pattern=>pattern.test(url)))
  const reply=(message,allowed)=>{
    if(message.__TAURI_INVOKE_KEY__!=='fixture-invoke-key')throw new Error('fixture invoke key mismatch')
    context.complete(allowed&&!reject?message.callback:message.error,allowed&&!reject?response:'FIXTURE_REJECTED')
  }
  const internals={__TAURI_PATTERN__:{pattern:'brownfield'}}
  if(!actualCore)internals.convertFileSrc=(cmd,protocol)=>`${protocol}://localhost/${encodeURIComponent(cmd)}`
  if(!deferMetadata)internals.metadata={currentWindow:{label:windowLabel},currentWebview:{label}}
  let nextRandom=0
  const window={crypto:{getRandomValues(view){view[0]=++nextRandom;return view}},__TAURI_INTERNALS__:internals,ipc:{postMessage(data){
    const message=JSON.parse(data)
    // Mirrors Wry WebKitGTK: source URI is supplied natively, never from payload.
    messages.push({message,source:page})
    reply(message,permitted(page,message.cmd))
  }}}
  context=vm.createContext({window,Headers,setTimeout,clearTimeout,console:{warn(...args){warnings.push(args.length)}},fetch(url,options){
    fetches.push({url,method:options.method,headers:[...options.headers],body:options.body})
    if(fetchMode==='pending')return new Promise(()=>{})
    if(fetchMode==='blocked')return Promise.reject(new Error('fixture access control'))
    // Mirrors Tauri parse_invoke_request: fetch source comes from Origin only.
    const command=decodeURIComponent(new URL(url).pathname.slice(1))
    const allowed=permitted(new URL(page).origin,command)&&!reject
    return Promise.resolve({headers:new Headers({'Tauri-Response':allowed?'ok':'error','content-type':'application/json'}),json:async()=>allowed?response:'FIXTURE_REJECTED'})
  }})
  vm.runInContext(render(candidate,os),context)
  if(actualCore) {
    vm.runInContext(upstreamIpc.replace('__TEMPLATE_isolation_origin__','"fixture-only"'),context)
    vm.runInContext(upstreamCore.replace('__TEMPLATE_os_name__',JSON.stringify(os)).replace('__TEMPLATE_protocol_scheme__','"http"'),context)
    context.complete=(id,value)=>internals.runCallback(id,value)
    context.callbackCount=()=>internals.callbacks.size
  } else {
  // Tauri's unchanged core owns callback registration and Promise settlement.
  // This synthetic core exercises that public transport contract without a GUI.
  vm.runInContext(`
    const callbacks=new Map();let next=0;
    globalThis.callbackCount=()=>callbacks.size;
    globalThis.complete=(id,value)=>callbacks.get(id)?.(value);
    Object.defineProperty(window.__TAURI_INTERNALS__,'runCallback',{value:complete});
    Object.defineProperty(window.__TAURI_INTERNALS__,'invoke',{value:(cmd,payload={},options)=>new Promise((resolve,reject)=>{
      const callback=++next,error=++next;
      callbacks.set(callback,value=>{callbacks.delete(callback);callbacks.delete(error);resolve(value)});
      callbacks.set(error,value=>{callbacks.delete(error);callbacks.delete(callback);reject(value)});
      window.__TAURI_INTERNALS__.postMessage({cmd,callback,error,payload,options});
    })});
  `,context)
  }
  const invokeCommand=(command,payload='{}',options='undefined')=>vm.runInContext(`window.__TAURI_INTERNALS__.invoke(${JSON.stringify(command)},${payload},${options})`,context)
  return {context,messages,fetches,warnings,run:script=>vm.runInContext(script,context),invokeCommand,invoke:(payload='{}',options='undefined')=>invokeCommand('accept_qmplus_auth',payload,options)}
}
const report=`{revision:7,report:{v:1,stage:'loading',document:'fixtureNonce',accountMatch:false,reason:'LOADING'}}`
const normalise=value=>JSON.stringify(value,(_key,item)=>Object.prototype.toString.call(item)==='[object ArrayBuffer]'?{binary:[...new Uint8Array(item)]}:item)

test('Linux startup installs the scoped transport before building the application',()=>{
  const app=read('src-tauri/src/lib.rs')
  assert.match(app,/#\[cfg\(target_os = "linux"\)\]\s*mod qmplus_linux_ipc;/)
  const run=app.slice(app.indexOf('pub fn run() {'))
  assert.match(run,/#\[cfg\(target_os = "linux"\)\]\s*let builder = qmplus_linux_ipc::configure\(builder\);/)
  assert.ok(run.indexOf('qmplus_linux_ipc::configure(builder)')<run.indexOf('.build(tauri::generate_context!())'))
})

test('the stock IPC and serializer copies are exact Tauri 2.12.1 bytes',()=>{
  assert.equal(hash(stock),'68ae690606006f733bde75dd8bb6748464954a22c7e83914a93b1abc221d7072')
  assert.equal(hash(serializer),'d51917f89e4d3d318d63f1f4f5a7ac7ea1399a5b85c81a840c4d606597f29132')
  assert.equal(hash(upstreamIpc),'3e3766fc90efa68003096cbf0a07c6a00cb31c5756d55b5a68ebbfd2930c4865')
  assert.equal(hash(upstreamCore),'71056442a732cca1f03572ccae96d68e16104c3a591c64de9618cd304e063070')
  assert.deepEqual([...read('src-tauri/Cargo.lock').matchAll(/name = "tauri"\nversion = "([^"]+)"/g)].map(match=>match[1]),['2.12.1'])
  assert.equal(stock.split('function sendIpcMessage(message) {').length,2)
  assert.match(source,/builder\.invoke_system\(initialization_script\(\)\)/)
  assert.match(source,/replace\("__TEMPLATE_invoke_key__", "__INVOKE_KEY__"\)/)
  assert.match(source,/replace\("function sendIpcMessage\(message\) \{", QMPLUS_DISPATCH\)/)
  assert.match(source,/#\[cfg\(not\(target_os = "linux"\)\)\]\s*\{\s*builder\s*\}/)
  assert.doesNotMatch(dispatch,/fetch\s*\(|location|document|cookie|storage|console|capabilit|credential|password/)
  assert.doesNotMatch(render(),/__TEMPLATE_|__RAW_|__INVOKE_KEY__/)
})

test('main view preserves stock fetch, headers, serializer, rejection and fallback behavior',async()=>{
  for(const fetchMode of ['ok','blocked'])for(const reject of [false,true])for(const payload of [report,'new Uint8Array([1,2,3])','new Uint8Array([4,5]).buffer','new Map([["fixture",7]])']) {
    const options={label:'main',page:'http://localhost:5173/',fetchMode,reject}
    const before=fixture({...options,candidate:false}),after=fixture(options)
    const outcomes=await Promise.all([before.invoke(payload).then(value=>['ok',value],error=>['error',error]),after.invoke(payload).then(value=>['ok',value],error=>['error',error])])
    assert.deepEqual(outcomes[0],outcomes[1])
    assert.equal(normalise(after.fetches),normalise(before.fetches))
    assert.equal(normalise(after.messages),normalise(before.messages))
    assert.deepEqual(after.warnings,before.warnings)
    assert.equal(after.context.callbackCount(),0)
  }
})

test('Linux QMplus chooses native IPC immediately even if fetch would never settle',async()=>{
  const f=fixture({fetchMode:'pending'})
  assert.equal(await f.invoke(report),true)
  assert.equal(f.fetches.length,0)
  assert.equal(f.messages.length,1)
  assert.equal(f.messages[0].message.options.customProtocolIpcBlocked,true)
  assert.equal(f.messages[0].message.__TAURI_INVOKE_KEY__,'fixture-invoke-key')
  assert.equal(f.context.callbackCount(),0)
})

test('native success and rejection both settle existing callbacks and release both IDs',async()=>{
  for(const reject of [false,true]) {
    const f=fixture({reject})
    if(reject)await assert.rejects(f.invoke(report),error=>error==='FIXTURE_REJECTED')
    else assert.equal(await f.invoke(report),true)
    assert.equal(f.context.callbackCount(),0)
    assert.equal(f.messages.length,1)
    assert.equal(f.fetches.length,0)
  }
})

// Binary values below are request payloads. Native raw responses may be JS arrays
// while fetch yields ArrayBuffer; these tests make no response-type equivalence claim.
test('native request envelope preserves stock serialization for binary values, Maps and IPC hooks',async()=>{
  const payloads=[
    ['new Uint8Array([2,4]).buffer',[2,4]],
    ['new Uint8Array([3,6])',[3,6]],
    ['new Map([["fixture",9]])',{fixture:9}],
    ['({__TAURI_TO_IPC_KEY__(){return {fixture:11}}})',{fixture:11}],
    ['({nested:new Uint8Array([5,10]).buffer})',{nested:[5,10]}],
  ]
  for(const [payload,expected] of payloads) {
    const f=fixture()
    await f.invoke(payload,'{headers:{"X-Fixture":"kept"},customProtocolIpcBlocked:false}')
    const message=f.messages[0].message
    assert.deepEqual(message.payload,expected)
    assert.equal(message.cmd,'accept_qmplus_auth')
    assert.deepEqual(message.options,{headers:{'X-Fixture':'kept'},customProtocolIpcBlocked:true})
    assert.equal(f.context.callbackCount(),0)
    const stockFallback=fixture({candidate:false,fetchMode:'blocked'})
    await stockFallback.invoke(payload,'{headers:{"X-Fixture":"kept"},customProtocolIpcBlocked:false}')
    assert.deepEqual(f.messages[0],stockFallback.messages[0])
  }
})

test('native source retains full tenant, KMSI and verification paths; unrelated paths stay denied',async()=>{
  for(const page of [tenant,'https://login.microsoftonline.com/kmsi','https://login.microsoftonline.com/common/DeviceAuthTls/reprocess']) {
    const f=fixture({page})
    assert.equal(await f.invoke(report),true)
    assert.equal(f.messages[0].source,page)
    assert.equal(capabilities.some(capability=>capability.patterns.some(pattern=>pattern.test(new URL(page).origin))),false)
  }
  const denied=fixture({page:'https://login.microsoftonline.com/common/unapproved'})
  await assert.rejects(denied.invoke(`{claimedSource:${JSON.stringify(tenant)},report:${report}}`),error=>error==='FIXTURE_REJECTED')
  assert.equal(denied.messages[0].source,'https://login.microsoftonline.com/common/unapproved')
})

test('metadata is consulted when sending, after Tauri finishes installing it',async()=>{
  const f=fixture({deferMetadata:true,fetchMode:'pending'})
  f.context.window.__TAURI_INTERNALS__.metadata={currentWindow:{label:'qmplus'},currentWebview:{label:'qmplus'}}
  assert.equal(await f.invoke(report),true)
  assert.equal(f.fetches.length,0)
})

test('other OS, other labels, mismatched labels and missing metadata retain stock sender',async()=>{
  for(const options of [{os:'macos'},{label:'main'},{label:'qmplus',windowLabel:'main'},{label:'main',windowLabel:'qmplus'},{deferMetadata:true}]) {
    const f=fixture({...options,fetchMode:'pending'})
    f.invoke(report)
    await flush()
    assert.equal(f.fetches.length,1)
    assert.equal(f.messages.length,0)
  }
})

test('postMessage is still installed once as a non-writable non-configurable property',()=>{
  const f=fixture()
  const descriptor=Object.getOwnPropertyDescriptor(f.context.window.__TAURI_INTERNALS__,'postMessage')
  assert.equal(descriptor.writable,false)
  assert.equal(descriptor.configurable,false)
  assert.equal(descriptor.enumerable,false)
  assert.equal(f.run('window.__TAURI_INTERNALS__.postMessage.toString()').includes('fixture-invoke-key'),false)
})

test('actual pinned Tauri ipc/core retain callbacks and request serialization across stock and native routes',async()=>{
  for(const label of ['main','qmplus'])for(const reject of [false,true])for(const payload of [report,'new Uint8Array([4,8]).buffer','({nested:new Map([["fixture",new Uint8Array([6,12])]])})']) {
    const options={actualCore:true,label,reject,page:label==='main'?'http://localhost:5173/':tenant}
    const baseline=fixture({...options,candidate:false,fetchMode:label==='qmplus'?'blocked':'ok'})
    const candidate=fixture({...options,fetchMode:label==='qmplus'?'pending':'ok'})
    const result=f=>f.invoke(payload).then(value=>['resolved',value],error=>['rejected',error])
    assert.deepEqual(await result(candidate),await result(baseline))
    assert.equal(candidate.context.callbackCount(),0)
    assert.equal(baseline.context.callbackCount(),0)
    assert.equal(normalise(candidate.messages),normalise(baseline.messages))
    if(label==='main')assert.equal(normalise(candidate.fetches),normalise(baseline.fetches))
    else assert.equal(candidate.fetches.length,0)
    assert.equal(typeof candidate.context.window.__TAURI_INTERNALS__.transformCallback,'function')
  }
})

test('verification capability permits auth only and denies sync, snapshot and main commands',async()=>{
  assert.deepEqual([...capabilities.find(capability=>capability.identifier==='qmplus-verification-inspection').commands],['accept_qmplus_auth'])
  for(const page of ['https://login.microsoftonline.com/common/DeviceAuthTls/reprocess','https://login.microsoftonline.com/common/deviceauthtls/reprocess']) {
    const f=fixture({page,actualCore:true})
    assert.equal(await f.invoke(report),true)
    for(const command of new Set(['begin_qmplus_sync','accept_qmplus_snapshot',...mainCommands,'plugin:event|listen','plugin:event|emit','plugin:fs|read_file'])) {
      await assert.rejects(f.invokeCommand(command),error=>error==='FIXTURE_REJECTED')
      assert.equal(f.context.callbackCount(),0)
    }
    assert.equal(f.fetches.length,0)
  }
  const tenantView=fixture({actualCore:true})
  for(const command of ['accept_qmplus_auth','begin_qmplus_sync','accept_qmplus_snapshot'])assert.equal(await tenantView.invokeCommand(command),true)
  await assert.rejects(tenantView.invokeCommand('load_qmplus'),error=>error==='FIXTURE_REJECTED')
})

test('current QMplus boolean and unit responses preserve values through actual core callbacks',async()=>{
  const signatures=read('src-tauri/src/qmplus.rs')
  for(const [command,responses,returnType] of [
    ['accept_qmplus_auth',[true,false],'bool'],
    ['begin_qmplus_sync',[null],'\\(\\)'],
    ['accept_qmplus_snapshot',[null],'\\(\\)'],
  ]) {
    assert.match(signatures,new RegExp(`pub fn ${command}\\([\\s\\S]*?\\) -> Result<${returnType}, String>`))
    for(const response of responses)for(const candidate of [true,false]) {
      const f=fixture({actualCore:true,candidate,response,fetchMode:candidate?'pending':'blocked'})
      assert.equal(await f.invokeCommand(command),response)
      assert.equal(f.context.callbackCount(),0)
      assert.equal(f.messages[0].message.options.customProtocolIpcBlocked,true)
    }
  }
})

test('channel requests keep the native blocked flag and remain denied by QMplus ACL',async()=>{
  const f=fixture({actualCore:true})
  await assert.rejects(f.invokeCommand('plugin:__TAURI_CHANNEL__|fetch','null','{headers:{"Tauri-Channel-Id":"fixture-channel"}}'),error=>error==='FIXTURE_REJECTED')
  const envelope=f.messages[0].message
  assert.equal(envelope.options.customProtocolIpcBlocked,true)
  assert.equal(envelope.options.headers['Tauri-Channel-Id'],'fixture-channel')
  assert.equal(f.fetches.length,0)
  assert.equal(f.context.callbackCount(),0)
})
