import test from 'node:test'
import assert from 'node:assert/strict'
import {spawnSync} from 'node:child_process'
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {fileURLToPath} from 'node:url'

const root=fileURLToPath(new URL('../',import.meta.url))
const read=relative=>readFileSync(path.join(root,relative))
const pinned=new Set([
  'src-tauri/src/qmplus_linux_ipc.rs',
  'test/fixtures/tauri-2.12.1/ipc.js',
  'test/fixtures/tauri-2.12.1/core.js',
])
const capabilityFiles=[
  'src-tauri/capabilities/default.json',
  'src-tauri/capabilities/qmplus.json',
  'src-tauri/capabilities/qmplus-verification.json',
]

test('IPC regression tests pass in an isolated CRLF checkout with exact LF upstream bytes',()=>{
  const directory=mkdtempSync(path.join(tmpdir(),'wts-ipc-crlf-checkout-'))
  try {
    const permissions=capabilityFiles.flatMap(relative=>JSON.parse(read(relative).toString('utf8')).permissions)
      .filter(identifier=>identifier.startsWith('allow-'))
      .map(identifier=>`src-tauri/permissions/autogenerated/${identifier.replace(/^allow-/,'').replaceAll('-','_')}.toml`)
    // Only repository source/configuration needed by this one test is copied.
    // The checkout regression itself is excluded, preventing recursive runs.
    const files=new Set([
      '.gitattributes','package.json','test/qmplus-linux-ipc.test.js',
      'src-tauri/src/lib.rs','src-tauri/src/qmplus.rs','src-tauri/Cargo.lock',
      ...pinned,...capabilityFiles,...permissions,
    ])
    for(const relative of files) {
      const original=read(relative)
      const bytes=pinned.has(relative)?original
        :Buffer.from(original.toString('utf8').replace(/\r\n/g,'\n').replace(/\n/g,'\r\n'))
      const target=path.join(directory,relative)
      mkdirSync(path.dirname(target),{recursive:true})
      writeFileSync(target,bytes)
      if(pinned.has(relative))assert.deepEqual(readFileSync(target),original)
      else assert.ok(bytes.includes(Buffer.from('\r\n')),relative)
    }
    // Nested node:test processes otherwise inherit the parent's IPC reporter
    // context, hiding individual TAP cases instead of running a fresh reporter.
    const childEnvironment={...process.env}
    delete childEnvironment.NODE_TEST_CONTEXT
    const child=spawnSync(process.execPath,[
      '--test','--test-reporter=tap',path.join(directory,'test/qmplus-linux-ipc.test.js'),
    ],{cwd:directory,env:childEnvironment,encoding:'utf8',timeout:30000,maxBuffer:4*1024*1024})
    assert.equal(child.error,undefined,child.error?.message)
    assert.equal(child.status,0,child.stdout+child.stderr)
    const required=[
      'Git pins IPC source and upstream fixture bytes to LF on every checkout',
      'portable capability matcher preserves exact origins, paths and terminal wildcard boundaries',
      'Linux startup installs the scoped transport before building the application',
      'the stock IPC and serializer copies are exact Tauri 2.12.1 bytes',
      'verification capability permits auth only and denies sync, snapshot and main commands',
      'current QMplus boolean and unit responses preserve values through actual core callbacks',
    ]
    const passedNames=child.stdout.split(/\r?\n/).filter(line=>/^ok \d+ - /.test(line))
      .map(line=>line.replace(/^ok \d+ - /,''))
    for(const name of required)assert.ok(passedNames.includes(name),name)
    assert.ok(Number(child.stdout.match(/^# pass (\d+)$/m)?.[1])>=16,child.stdout)
    assert.match(child.stdout,/^# fail 0$/m)
    assert.match(child.stdout,/^# skipped 0$/m)
    for(const relative of pinned)assert.deepEqual(readFileSync(path.join(directory,relative)),read(relative))
  } finally {
    rmSync(directory,{recursive:true,force:true})
  }
})
